### ISSUE TITLE
Role Sync does not work

### ISSUE THREAD

**Issue by Bazimek** [SCPStats/Plugin#50]
I set everything and still role sync does not work.

**Comment by Liassid** [comment]
Hey. Please show your SCPStats config. Did you link SCPStats server to a discord server?

**Comment by PintTheDragon** [comment]
Please ask for support for issues such as this in the SCPStats discord server (https://discord.gg/jKBEJCk7QB) or in the EXILED discord because it's probably a config issue.

**Comment by Bazimek** [comment]
> 

Hello, Yes I use the !link command sucessfully. My fonfig is here:

scp_stats:
  is_enabled: true
  # Turning this off will disable the auto updater, which will automatically update the plugin.
  auto_updates: true
  # If you enable this option, bans will automatically be synced across every server linked together.
  sync_bans: false
  # If you enable this, bans will only be saved to SCPStats and will not be saved to the bans file. This fixes a bug where players must be unbanned on the server they were banned on, or else they will be unbanned on every server but that one. This does not affect already existing bans.
  disable_basegame_bans: false
  # By default, SCPStats does not require confirmation that a user is not banned (and will only kick them if it confirms that they are banned). This is fine, but makes it possible to bypass bans with a DDOS attack. Turning this on will kick players if they are not confirmed to not be banned.
  require_confirmation: false
  # The delay (in seconds) for preauth requests on the first round of the game.
  first_round_preauth_delay: 4
  # The role that should be given to nitro boosters. Your server must be linked to your discord server to do this.
  booster_role: none
  # The role that should be given to discord members. Your server must be linked to your discord server to do this.
  discord_member_role: none
  # Roles that you want to sync. Adding a role here means that if the person has the role on discord, they will get it in game. If a user has multiple roles that can be synced, the highest role in this list will be chosen. Your server must be linked to your discord server to do this. You can also give roles based on how the player ranks in certain stats. For example, you can give 20 players with the highest playtime a role with the example role. All of the possible metrics are: "kills", "deaths", "rounds", "playtime", "sodas", "medkits", "balls", "adrenaline", "escapes", "xp", "fastestescape", "level", "playtime30", "playtime7", and "playtime1".
  role_sync:
  - 911374953067196446:vip
  # Allows you to modify the name of a role, per-person. For example, you could modify a role's name to include the xp and level of of the person who has it. The key (left value) is the name of the role (not what's displayed ingame, but what's used in the remote admin configs). The value (right value) is the new name for the role. Inside of it, you can place metrics, surrounded by a "{" and "}" on either side. For example, "{xp} XP". See above for information on the available values for this.
  role_names:
    ExampleXPRole: '{xp} XP | Level {level}'
  # The whitelist will only allow a player to join the server if they meet certain conditions. See the below options for how to change the whitelist's behavior. The whitelist is just a list of the same conditions used in rolesync (so only the left side, without the : ), with the addition of "discordmember" and "booster" being valid conditions.
  whitelist:
  - DiscordRoleID
  # By default, the whitelist will allow a person in if they match any of the conditions. Setting this value to true will mean that a person will only be let in if every condition matches.
  whitelist_require_all: false
  # Reserved slots will allow a player to join a full server, but only if they meet certain conditions. See the below options for how to change the reserved slots list' behavior. The reserved slots list is just a list of the same conditions used in rolesync (so only the left side, without the : ), with the addition of "discordmember" and "booster" being valid conditions.
  reserved_slots:
  - DiscordRoleID
  # By default, a player will have a reserved slot if they match any of the conditions. Setting this value to true will mean that a person will only be let in if every condition matches.

**Comment by PintTheDragon** [comment]
What is the SCPStats server id?

**Comment by Bazimek** [comment]
I did not know you need a scpstats account. So I think that will be the issue. Sorry about that.
